version: 2
jobs:

  # Run tests.
  Test:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: pyenv global 3.6.5
      - restore_cache:
          keys:
            - test-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - test-dependencies-
      - run: sudo add-apt-repository -y ppa:migurski/planscore
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libgeos-c1v5=3.5.1-3~xenial0 libgdal20=2.2.2+dfsg-1~xenial1 libgdal-dev=2.2.2+dfsg-1~xenial1 libspatialindex-dev
      - run: CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip3 install "GDAL <= `gdal-config --version`"
      - run: pip3 install .[convert]
      - save_cache:
          paths:
            - /opt/circleci/.pyenv
          key: test-dependencies-{{ checksum "setup.py" }}
      - run: python3 setup.py test

  # Prepare Lambda package for use in Deploy step.
  # Optimistically prepares images in parallel with Test step.
  Build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: pyenv global 3.6.5
      - restore_cache:
          keys:
            - build-dependencies-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run: make dgraphs-lambda.zip
      - save_cache:
          paths:
            - ~/.cache/pip
          key: build-dependencies-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dgraphs-lambda.zip
            - gdal-geos-python.tar.gz
  
  # Deploy to Lambda using package from Build step.
  Deploy:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run: pyenv global 3.6.5
      - restore_cache:
          keys:
            - deploy-dependencies-{{ checksum ".circleci/config.yml" }}
      - run: pip install boto3
      - save_cache:
          paths:
            - ~/.cache/pip
          key: deploy-dependencies-{{ checksum ".circleci/config.yml" }}
      - attach_workspace:
          at: ~/repo
      - run: make live-lambda

workflows:
  version: 2
  everything:
    jobs:
      - Test
      - Build
      - Deploy:
          requires:
            - Test
            - Build
